import 'dart:math';

import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:uuid/uuid.dart';
import 'package:lecto/core/database/database.dart';
import 'package:lecto/core/database/providers.dart';
import 'package:lecto/core/services/book_search_service.dart';
import 'package:lecto/features/books/providers/book_providers.dart';

part 'recommendation_providers.g.dart';

// ============================================================
// Service instances
// ============================================================

final _bookSearchService = BookSearchService();
final _uuid = const Uuid();

// ============================================================
// Recommendations list
// ============================================================

/// Provides the list of non-dismissed recommendations from the database,
/// ordered by score (highest first).
@Riverpod(keepAlive: true)
Future<List<Recommendation>> recommendations(RecommendationsRef ref) async {
  final db = ref.watch(databaseProvider);
  return db.getRecommendations();
}

// ============================================================
// Recommendation engine
// ============================================================

/// Represents a single recommendation generated by the engine.
class GeneratedRecommendation {
  final String title;
  final String author;
  final String? coverUrl;
  final String? description;
  final String recommendationType; // 'genre_similar', 'author_similar', 'popular'
  final double score;

  const GeneratedRecommendation({
    required this.title,
    required this.author,
    this.coverUrl,
    this.description,
    required this.recommendationType,
    this.score = 1.0,
  });
}

/// Generates book recommendations by analyzing the user's finished books
/// (genres and authors) and fetching similar books via the Google Books API.
///
/// Strategy:
///   1. Collect the top genres from finished books.
///   2. Collect popular authors from finished books.
///   3. For each genre, fetch similar books via Google Books.
///   4. For each author, fetch more books by that author.
///   5. Score, deduplicate, and save the results.
@Riverpod(keepAlive: true)
class RecommendationEngine extends _$RecommendationEngine {
  @override
  Future<List<Recommendation>> build() async {
    // On first build, run the engine automatically.
    // This provider acts as the trigger; call `generate()` manually to refresh.
    return [];
  }

  /// Generates recommendations and persists them to the database.
  ///
  /// Returns the newly generated list of [Recommendation]s.
  Future<List<Recommendation>> generate() async {
    final db = ref.read(databaseProvider);

    // Get finished books
    final finishedBooks = db.getBooksByStatus(ReadingStatus.finished);
    if (finishedBooks.isEmpty) {
      // No finished books — fetch popular books by a broad search
      return _generateFallbackRecommendations(db);
    }

    // Collect genres and authors from finished books
    final genreCount = <String, int>{};
    final authorCount = <String, int>{};
    final existingIsbns = <String>{};

    for (final book in finishedBooks) {
      if (book.author.isNotEmpty && book.author != 'Unknown Author') {
        authorCount[book.author] = (authorCount[book.author] ?? 0) + 1;
      }
      for (final cat in book.categories) {
        genreCount[cat] = (genreCount[cat] ?? 0) + 1;
      }
      if (book.isbn != null) {
        existingIsbns.add(book.isbn!);
      }
    }

    // Sort to get the top genres and authors
    final topGenres = genreCount.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final topAuthors = authorCount.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    final allCandidates = <GeneratedRecommendation>{};
    final seenTitles = <String>{};

    // Fetch similar books by genre
    for (final entry in topGenres.take(3)) {
      try {
        final results = await _bookSearchService.getSimilarBooks(entry.key);
        for (final result in results) {
          final title = (result['title'] as String?)?.trim().toLowerCase();
          if (title == null || title.isEmpty) continue;
          if (seenTitles.contains(title)) continue;
          seenTitles.add(title);

          allCandidates.add(GeneratedRecommendation(
            title: result['title'] as String? ?? '',
            author: result['author'] as String? ?? 'Unknown Author',
            coverUrl: result['coverUrl'] as String?,
            description: result['description'] as String?,
            recommendationType: 'genre_similar',
            score: 0.9,
          ));
        }
      } catch (_) {
        // Continue with other genres if one fails
      }
    }

    // Fetch similar books by author
    for (final entry in topAuthors.take(3)) {
      try {
        final searchResult = await _bookSearchService.searchBooks('inauthor:"${entry.key}"');
        for (final bookData in searchResult.books) {
          final title = (bookData['title'] as String?)?.trim().toLowerCase();
          if (title == null || title.isEmpty) continue;
          if (seenTitles.contains(title)) continue;
          seenTitles.add(title);

          allCandidates.add(GeneratedRecommendation(
            title: bookData['title'] as String? ?? '',
            author: bookData['author'] as String? ?? 'Unknown Author',
            coverUrl: bookData['coverUrl'] as String?,
            description: bookData['description'] as String?,
            recommendationType: 'author_similar',
            score: 0.85,
          ));
        }
      } catch (_) {
        // Continue with other authors if one fails
      }
    }

    // Limit to the top 20 recommendations
    final finalCandidates = allCandidates.take(20).toList();

    // Save to database — use Recommendation model with full metadata
    final now = DateTime.now();
    final recsToSave = <Recommendation>[];

    for (final candidate in finalCandidates) {
      // Generate a deterministic-ish ID from the title
      final id = _uuid.v5(
        Uuid.NAMESPACE_URL,
        'recommendation://${candidate.title}',
      );

      recsToSave.add(Recommendation(
        id: id,
        bookId: id, // We'll use the same ID, matching a potential future book entry
        title: candidate.title,
        author: candidate.author,
        coverUrl: candidate.coverUrl,
        recommendationType: candidate.recommendationType,
        score: candidate.score,
        generatedAt: now,
        dismissed: false,
      ));
    }

    // Clear old recommendations and save new ones
    db.clearRecommendations();
    db.saveRecommendations(recsToSave);

    // Build a mapping from book IDs so the Recommendation objects are useful
    // For now, return what the DB has
    final savedRecs = db.getRecommendations();

    // Invalidate dependent providers
    ref.invalidate(recommendationsProvider);

    return savedRecs;
  }

  /// Fallback when the user has no finished books: fetch popular books by genre.
  Future<List<Recommendation>> _generateFallbackRecommendations(AppDatabase db) async {
    final popularGenres = ['fiction', 'fantasy', 'science fiction', 'mystery', 'romance'];
    final now = DateTime.now();
    final recsToSave = <Recommendation>[];
    final seenTitles = <String>{};

    for (final genre in popularGenres) {
      try {
        final results = await _bookSearchService.getSimilarBooks(genre);
        for (final result in results) {
          final title = (result['title'] as String?)?.trim().toLowerCase();
          if (title == null || title.isEmpty) continue;
          if (seenTitles.contains(title)) continue;
          seenTitles.add(title);

          final id = _uuid.v5(
            Uuid.NAMESPACE_URL,
            'recommendation://$title',
          );

          recsToSave.add(Recommendation(
            id: id,
            bookId: id,
            title: result['title'] as String? ?? '',
            author: result['author'] as String? ?? 'Auteur inconnu',
            coverUrl: result['coverUrl'] as String?,
            recommendationType: 'popular',
            score: 0.7,
            generatedAt: now,
            dismissed: false,
          ));

          if (recsToSave.length >= 20) break;
        }
      } catch (_) {
        continue;
      }
      if (recsToSave.length >= 20) break;
    }

    db.clearRecommendations();
    db.saveRecommendations(recsToSave);

    ref.invalidate(recommendationsProvider);
    return db.getRecommendations();
  }
}

// ============================================================
// Dismiss a recommendation
// ============================================================

/// Marks a recommendation as dismissed in the database.
@Riverpod(keepAlive: true)
class DismissRecommendation extends _$DismissRecommendation {
  @override
  Future<void> build(String recommendationId) {
    throw UnimplementedError('Use ref.read(dismissRecommendationProvider(id).notifier).dismiss()');
  }

  /// Marks the recommendation as dismissed and invalidates the list.
  Future<void> dismiss() async {
    final db = ref.read(databaseProvider);
    db.dismissRecommendation(recommendationId);
    ref.invalidate(recommendationsProvider);
  }
}
