// Generated by Drift for the Lecto database
// This file contains the database and table definitions without code generation

import 'dart:convert';
import 'dart:io' show Platform;

import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';
import 'package:sqlite3/sqlite3.dart' as sqlite3;
import 'package:uuid/uuid.dart';

// ============================================================
// SQLite3 Database helper extensions
// ============================================================

/// Extension methods to provide insert/update/delete convenience
/// on the raw [sqlite3.Database] (mimicking Drift's API).
extension Sqlite3DatabaseHelper on sqlite3.Database {
  void insert(String table, Map<String, dynamic> values) {
    final columns = values.keys.join(', ');
    final placeholders = values.keys.map((_) => '?').join(', ');
    execute('INSERT INTO $table ($columns) VALUES ($placeholders)', values.values.toList());
  }

  int update(String table, Map<String, dynamic> values, {String? where, List<Object?>? whereArgs}) {
    final setClause = values.keys.map((k) => '$k = ?').join(', ');
    final allArgs = [...values.values, ...?whereArgs];
    final sql = 'UPDATE $table SET $setClause${where != null ? ' WHERE $where' : ''}';
    execute(sql, allArgs);
    return 0; // sqlite3 doesn't expose row count via a property
  }

  int delete(String table, {String? where, List<Object?>? whereArgs}) {
    final sql = 'DELETE FROM $table${where != null ? ' WHERE $where' : ''}';
    execute(sql, whereArgs ?? []);
    return 0; // sqlite3 doesn't expose row count via a property
  }
}

// ============================================================
// Reading Status Enum
// ============================================================
enum ReadingStatus { wantToRead, reading, finished, abandoned }

// ============================================================
// Data classes
// ============================================================
class Book {
  final String id;
  final String title;
  final String author;
  final String? isbn;
  final String? description;
  final String? coverUrl;
  final String? publisher;
  final String? publishedDate;
  final int? pageCount;
  final List<String> categories;
  final String? language;
  final ReadingStatus status;
  final double? myRating;
  final String? notes;
  final DateTime dateAdded;
  final DateTime? dateStarted;
  final DateTime? dateFinished;

  Book({
    required this.id,
    required this.title,
    required this.author,
    this.isbn,
    this.description,
    this.coverUrl,
    this.publisher,
    this.publishedDate,
    this.pageCount,
    this.categories = const [],
    this.language,
    this.status = ReadingStatus.wantToRead,
    this.myRating,
    this.notes,
    DateTime? dateAdded,
    this.dateStarted,
    this.dateFinished,
  }) : dateAdded = dateAdded ?? DateTime.now();

  Map<String, dynamic> toMap() => {
        'id': id,
        'title': title,
        'author': author,
        'isbn': isbn,
        'description': description,
        'cover_url': coverUrl,
        'publisher': publisher,
        'published_date': publishedDate,
        'page_count': pageCount,
        'categories': jsonEncode(categories),
        'language': language,
        'status': status.name,
        'my_rating': myRating,
        'notes': notes,
        'date_added': dateAdded.toIso8601String(),
        'date_started': dateStarted?.toIso8601String(),
        'date_finished': dateFinished?.toIso8601String(),
      };

  factory Book.fromMap(Map<String, dynamic> map) => Book(
        id: map['id'] as String,
        title: map['title'] as String,
        author: map['author'] as String,
        isbn: map['isbn'] as String?,
        description: map['description'] as String?,
        coverUrl: map['cover_url'] as String?,
        publisher: map['publisher'] as String?,
        publishedDate: map['published_date'] as String?,
        pageCount: map['page_count'] as int?,
        categories: map['categories'] != null
            ? List<String>.from(jsonDecode(map['categories'] as String))
            : [],
        language: map['language'] as String?,
        status: ReadingStatus.values.firstWhere(
            (s) => s.name == map['status'],
            orElse: () => ReadingStatus.wantToRead),
        myRating: (map['my_rating'] as num?)?.toDouble(),
        notes: map['notes'] as String?,
        dateAdded: DateTime.parse(map['date_added'] as String),
        dateStarted: map['date_started'] != null
            ? DateTime.parse(map['date_started'] as String)
            : null,
        dateFinished: map['date_finished'] != null
            ? DateTime.parse(map['date_finished'] as String)
            : null,
      );

  Book copyWith({
    String? id,
    String? title,
    String? author,
    String? isbn,
    String? description,
    String? coverUrl,
    String? publisher,
    String? publishedDate,
    int? pageCount,
    List<String>? categories,
    String? language,
    ReadingStatus? status,
    double? myRating,
    String? notes,
    DateTime? dateAdded,
    DateTime? dateStarted,
    DateTime? dateFinished,
  }) =>
      Book(
        id: id ?? this.id,
        title: title ?? this.title,
        author: author ?? this.author,
        isbn: isbn ?? this.isbn,
        description: description ?? this.description,
        coverUrl: coverUrl ?? this.coverUrl,
        publisher: publisher ?? this.publisher,
        publishedDate: publishedDate ?? this.publishedDate,
        pageCount: pageCount ?? this.pageCount,
        categories: categories ?? this.categories,
        language: language ?? this.language,
        status: status ?? this.status,
        myRating: myRating ?? this.myRating,
        notes: notes ?? this.notes,
        dateAdded: dateAdded ?? this.dateAdded,
        dateStarted: dateStarted ?? this.dateStarted,
        dateFinished: dateFinished ?? this.dateFinished,
      );
}

class ReadingSession {
  final String id;
  final String bookId;
  final DateTime startTime;
  final DateTime? endTime;
  final int? startPage;
  final int? endPage;
  final int? pagesRead;
  final int? durationSeconds;
  final String? note;

  ReadingSession({
    required this.id,
    required this.bookId,
    required this.startTime,
    this.endTime,
    this.startPage,
    this.endPage,
    this.pagesRead,
    this.durationSeconds,
    this.note,
  });

  Duration? get duration =>
      durationSeconds != null ? Duration(seconds: durationSeconds!) : null;

  Map<String, dynamic> toMap() => {
        'id': id,
        'book_id': bookId,
        'start_time': startTime.toIso8601String(),
        'end_time': endTime?.toIso8601String(),
        'start_page': startPage,
        'end_page': endPage,
        'pages_read': pagesRead,
        'duration_seconds': durationSeconds,
        'note': note,
      };

  factory ReadingSession.fromMap(Map<String, dynamic> map) => ReadingSession(
        id: map['id'] as String,
        bookId: map['book_id'] as String,
        startTime: DateTime.parse(map['start_time'] as String),
        endTime: map['end_time'] != null
            ? DateTime.parse(map['end_time'] as String)
            : null,
        startPage: map['start_page'] as int?,
        endPage: map['end_page'] as int?,
        pagesRead: map['pages_read'] as int?,
        durationSeconds: map['duration_seconds'] as int?,
        note: map['note'] as String?,
      );
}

class ReadingGoal {
  final String id;
  final int year;
  final int? month;
  final String type; // 'books', 'pages', 'minutes'
  final int target;
  final int progress;

  ReadingGoal({
    required this.id,
    required this.year,
    this.month,
    required this.type,
    required this.target,
    this.progress = 0,
  });

  double get percentage => target > 0 ? (progress / target).clamp(0.0, 1.0) : 0.0;
  bool get isComplete => progress >= target;
  int get remaining => (target - progress).clamp(0, target);

  Map<String, dynamic> toMap() => {
        'id': id,
        'year': year,
        'month': month,
        'type': type,
        'target': target,
        'progress': progress,
      };

  factory ReadingGoal.fromMap(Map<String, dynamic> map) => ReadingGoal(
        id: map['id'] as String,
        year: map['year'] as int,
        month: map['month'] as int?,
        type: map['type'] as String,
        target: map['target'] as int,
        progress: map['progress'] as int? ?? 0,
      );
}

class Recommendation {
  final String id;
  final String bookId;
  final String title;
  final String author;
  final String? coverUrl;
  final String recommendationType;
  final double score;
  final DateTime generatedAt;
  final bool dismissed;

  Recommendation({
    required this.id,
    required this.bookId,
    required this.title,
    required this.author,
    this.coverUrl,
    required this.recommendationType,
    required this.score,
    DateTime? generatedAt,
    this.dismissed = false,
  }) : generatedAt = generatedAt ?? DateTime.now();

  Map<String, dynamic> toMap() => {
        'id': id,
        'book_id': bookId,
        'title': title,
        'author': author,
        'cover_url': coverUrl,
        'recommendation_type': recommendationType,
        'score': score,
        'generated_at': generatedAt.toIso8601String(),
        'dismissed': dismissed ? 1 : 0,
      };

  factory Recommendation.fromMap(Map<String, dynamic> map) => Recommendation(
        id: map['id'] as String,
        bookId: map['book_id'] as String,
        title: map['title'] as String? ?? 'Titre inconnu',
        author: map['author'] as String? ?? 'Auteur inconnu',
        coverUrl: map['cover_url'] as String?,
        recommendationType: map['recommendation_type'] as String,
        score: (map['score'] as num).toDouble(),
        generatedAt: DateTime.parse(map['generated_at'] as String),
        dismissed: map['dismissed'] == 1,
      );
}

// ============================================================
// Database
// ============================================================
class AppDatabase {
  static AppDatabase? _instance;

  /// Returns the singleton instance, throwing [StateError] if not initialized.
  static AppDatabase get instance {
    if (_instance == null) {
      throw StateError('Database not initialized. Call AppDatabase.create() first.');
    }
    return _instance!;
  }

  final sqlite3.Database _db;
  final _uuid = const Uuid();

  AppDatabase._(this._db);

  static Future<AppDatabase> create() async {
    if (_instance != null) return _instance!;

    final dbFolder = await getApplicationDocumentsDirectory();
    final file = p.join(dbFolder.path, 'lecto.sqlite3');

    if (Platform.isAndroid) {
      await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    }

    final db = sqlite3.sqlite3.open(file, uri: true);
    db.execute('PRAGMA journal_mode=WAL');
    db.execute('PRAGMA foreign_keys=ON');

    _instance = AppDatabase._(db);
    await _instance!._createTables();
    return _instance!;
  }

  Future<void> _createTables() async {
    _db.execute('''
      CREATE TABLE IF NOT EXISTS books (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        author TEXT NOT NULL,
        isbn TEXT,
        description TEXT,
        cover_url TEXT,
        publisher TEXT,
        published_date TEXT,
        page_count INTEGER,
        categories TEXT,
        language TEXT,
        status TEXT NOT NULL DEFAULT 'wantToRead',
        my_rating REAL,
        notes TEXT,
        date_added TEXT NOT NULL,
        date_started TEXT,
        date_finished TEXT
      )
    ''');

    _db.execute('''
      CREATE TABLE IF NOT EXISTS reading_sessions (
        id TEXT PRIMARY KEY,
        book_id TEXT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
        start_time TEXT NOT NULL,
        end_time TEXT,
        start_page INTEGER,
        end_page INTEGER,
        pages_read INTEGER,
        duration_seconds INTEGER,
        note TEXT
      )
    ''');

    _db.execute('''
      CREATE TABLE IF NOT EXISTS reading_goals (
        id TEXT PRIMARY KEY,
        year INTEGER NOT NULL,
        month INTEGER,
        type TEXT NOT NULL,
        target INTEGER NOT NULL,
        progress INTEGER NOT NULL DEFAULT 0
      )
    ''');

    _db.execute('''
      CREATE TABLE IF NOT EXISTS recommendations (
        id TEXT PRIMARY KEY,
        book_id TEXT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
        title TEXT NOT NULL DEFAULT '',
        author TEXT NOT NULL DEFAULT '',
        cover_url TEXT,
        recommendation_type TEXT NOT NULL,
        score REAL NOT NULL,
        generated_at TEXT NOT NULL,
        dismissed INTEGER NOT NULL DEFAULT 0
      )
    ''');

    // Migration: add title/author/cover_url columns if they don't exist
    _migrateRecommendationsTable();
  }

  // ============================================================
  // Books CRUD
  // ============================================================

  Future<Book> addBook(Book book) async {
    final id = book.id.isEmpty ? _uuid.v4() : book.id;
    final b = book.copyWith(id: id);
    _db.insert('books', b.toMap());
    return b;
  }

  Book? getBook(String id) {
    final result = _db.select('SELECT * FROM books WHERE id = ?', [id]);
    if (result.isEmpty) return null;
    return Book.fromMap(result.first);
  }

  List<Book> getAllBooks({String? search}) {
    late List<Map<String, dynamic>> rows;
    if (search != null && search.isNotEmpty) {
      final q = '%$search%';
      rows = _db.select(
        'SELECT * FROM books WHERE title LIKE ? OR author LIKE ? OR isbn LIKE ? ORDER BY date_added DESC',
        [q, q, q],
      );
    } else {
      rows = _db.select('SELECT * FROM books ORDER BY date_added DESC');
    }
    return rows.map((r) => Book.fromMap(r)).toList();
  }

  List<Book> getBooksByStatus(ReadingStatus status) {
    final rows = _db.select(
      'SELECT * FROM books WHERE status = ? ORDER BY date_added DESC',
      [status.name],
    );
    return rows.map((r) => Book.fromMap(r)).toList();
  }

  int updateBook(String id, Map<String, dynamic> updates) {
    final existing = getBook(id);
    if (existing == null) return 0;
    return _db.update('books', updates, where: 'id = ?', whereArgs: [id]);
  }

  int deleteBook(String id) {
    return _db.delete('books', where: 'id = ?', whereArgs: [id]);
  }

  // ============================================================
  // Reading Sessions CRUD
  // ============================================================

  ReadingSession startSession(String bookId, {int? startPage}) {
    final id = _uuid.v4();
    final session = ReadingSession(
      id: id,
      bookId: bookId,
      startTime: DateTime.now(),
      startPage: startPage,
    );
    _db.insert('reading_sessions', session.toMap());
    return session;
  }

  ReadingSession? getSession(String id) {
    final result = _db.select('SELECT * FROM reading_sessions WHERE id = ?', [id]);
    if (result.isEmpty) return null;
    return ReadingSession.fromMap(result.first);
  }

  void endSession(String id, {int? endPage, int? pagesRead, Duration? customDuration}) {
    final now = DateTime.now();
    final session = getSession(id);
    if (session == null) return;
    final duration = customDuration ?? now.difference(session.startTime);
    final updates = <String, dynamic>{
      'end_time': now.toIso8601String(),
      'end_page': endPage,
      'pages_read': pagesRead ?? (endPage != null && session.startPage != null ? endPage - session.startPage! : null),
      'duration_seconds': duration.inSeconds,
    };
    _db.update('reading_sessions', updates, where: 'id = ?', whereArgs: [id]);
  }

  List<ReadingSession> getSessionsForBook(String bookId) {
    final rows = _db.select(
      'SELECT * FROM reading_sessions WHERE book_id = ? ORDER BY start_time DESC',
      [bookId],
    );
    return rows.map((r) => ReadingSession.fromMap(r)).toList();
  }

  List<ReadingSession> getAllSessions() {
    final rows = _db.select('SELECT * FROM reading_sessions ORDER BY start_time DESC');
    return rows.map((r) => ReadingSession.fromMap(r)).toList();
  }

  void deleteSession(String id) {
    _db.delete('reading_sessions', where: 'id = ?', whereArgs: [id]);
  }

  /// Returns the total number of pages read across all sessions for a book.
  int getTotalPagesReadForBook(String bookId) {
    final result = _db.select(
      'SELECT COALESCE(SUM(pages_read), 0) as total FROM reading_sessions WHERE book_id = ? AND pages_read IS NOT NULL',
      [bookId],
    );
    return result.first['total'] as int;
  }

  /// Returns the most recent active session (no end_time) for a book, if any.
  ReadingSession? getActiveSessionForBook(String bookId) {
    final rows = _db.select(
      'SELECT * FROM reading_sessions WHERE book_id = ? AND end_time IS NULL ORDER BY start_time DESC LIMIT 1',
      [bookId],
    );
    if (rows.isEmpty) return null;
    return ReadingSession.fromMap(rows.first);
  }

  /// Updates a session's pages read, end page, and duration (for manual entry).
  void updateSessionPages(String id, {required int pagesRead, int? endPage, int? durationSeconds}) {
    final now = DateTime.now();
    final updates = <String, dynamic>{
      'pages_read': pagesRead,
      'end_page': endPage,
      'end_time': now.toIso8601String(),
      'duration_seconds': durationSeconds,
    };
    _db.update('reading_sessions', updates, where: 'id = ?', whereArgs: [id]);
  }

  // ============================================================
  // Goals CRUD
  // ============================================================

  ReadingGoal setGoal(ReadingGoal goal) {
    final id = goal.id.isEmpty ? _uuid.v4() : goal.id;
    final g = ReadingGoal(
      id: id,
      year: goal.year,
      month: goal.month,
      type: goal.type,
      target: goal.target,
      progress: goal.progress,
    );
    _db.insert('reading_goals', g.toMap());
    return g;
  }

  ReadingGoal? getGoal(String id) {
    final result = _db.select('SELECT * FROM reading_goals WHERE id = ?', [id]);
    if (result.isEmpty) return null;
    return ReadingGoal.fromMap(result.first);
  }

  List<ReadingGoal> getGoals({int? year, int? month}) {
    late List<Map<String, dynamic>> rows;
    if (year != null && month != null) {
      rows = _db.select(
        'SELECT * FROM reading_goals WHERE year = ? AND month = ?',
        [year, month],
      );
    } else if (year != null) {
      rows = _db.select(
        'SELECT * FROM reading_goals WHERE year = ?',
        [year],
      );
    } else {
      rows = _db.select('SELECT * FROM reading_goals');
    }
    return rows.map((r) => ReadingGoal.fromMap(r)).toList();
  }

  void updateGoalProgress(String id, int progress) {
    _db.update('reading_goals', {'progress': progress}, where: 'id = ?', whereArgs: [id]);
  }

  void deleteGoal(String id) {
    _db.delete('reading_goals', where: 'id = ?', whereArgs: [id]);
  }

  // ============================================================
  // Recommendations
  // ============================================================

  void saveRecommendations(List<Recommendation> recs) {
    for (final rec in recs) {
      _db.insert('recommendations', rec.toMap());
    }
  }

  List<Recommendation> getRecommendations({bool includeDismissed = false}) {
    final rows = includeDismissed
        ? _db.select('SELECT * FROM recommendations ORDER BY score DESC')
        : _db.select(
            'SELECT * FROM recommendations WHERE dismissed = 0 ORDER BY score DESC');
    return rows.map((r) => Recommendation.fromMap(r)).toList();
  }

  void dismissRecommendation(String id) {
    _db.update('recommendations', {'dismissed': 1}, where: 'id = ?', whereArgs: [id]);
  }

  void clearRecommendations() {
    _db.delete('recommendations');
  }

  // ============================================================
  // Stats queries
  // ============================================================

  int totalBooksRead() {
    final result = _db.select(
      'SELECT COUNT(*) as count FROM books WHERE status = ?',
      ['finished'],
    );
    return result.first['count'] as int;
  }

  int totalPagesRead() {
    final result = _db.select(
      'SELECT COALESCE(SUM(pages_read), 0) as total FROM reading_sessions',
    );
    return result.first['total'] as int;
  }

  Duration totalReadingTime() {
    final result = _db.select(
      'SELECT COALESCE(SUM(duration_seconds), 0) as total FROM reading_sessions',
    );
    return Duration(seconds: result.first['total'] as int);
  }

  int currentStreak() {
    final rows = _db.select('''
      SELECT DISTINCT DATE(end_time) as read_date 
      FROM reading_sessions 
      WHERE end_time IS NOT NULL 
      ORDER BY read_date DESC
    ''');

    if (rows.isEmpty) return 0;

    final dates = rows.map((r) => r['read_date'] as String).toList();
    final today = DateTime.now();
    final todayStr = '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';
    final yesterday = today.subtract(const Duration(days: 1));
    final yesterdayStr = '${yesterday.year}-${yesterday.month.toString().padLeft(2, '0')}-${yesterday.day.toString().padLeft(2, '0')}';

    if (dates.first != todayStr && dates.first != yesterdayStr) return 0;

    int streak = 0;
    final allDates = dates.map((d) => DateTime.parse(d)).toList();
    for (int i = 0; i < allDates.length; i++) {
      if (i == 0) {
        streak = 1;
        continue;
      }
      final diff = allDates[i - 1].difference(allDates[i]).inDays;
      if (diff == 1) {
        streak++;
      } else {
        break;
      }
    }
    return streak;
  }

  Map<int, int> monthlyPages(int year) {
    final result = <int, int>{};
    for (int m = 1; m <= 12; m++) result[m] = 0;

    final rows = _db.select('''
      SELECT CAST(strftime('%m', start_time) AS INTEGER) as month,
             COALESCE(SUM(pages_read), 0) as total
      FROM reading_sessions
      WHERE pages_read IS NOT NULL
        AND CAST(strftime('%Y', start_time) AS INTEGER) = ?
      GROUP BY month
      ORDER BY month
    ''', [year]);

    for (final row in rows) {
      result[row['month'] as int] = (row['total'] as num).toInt();
    }
    return result;
  }

  Map<int, int> monthlyDuration(int year) {
    final result = <int, int>{};
    for (int m = 1; m <= 12; m++) result[m] = 0;

    final rows = _db.select('''
      SELECT CAST(strftime('%m', start_time) AS INTEGER) as month,
             COALESCE(SUM(duration_seconds), 0) as total
      FROM reading_sessions
      WHERE duration_seconds IS NOT NULL
        AND CAST(strftime('%Y', start_time) AS INTEGER) = ?
      GROUP BY month
      ORDER BY month
    ''', [year]);

    for (final row in rows) {
      result[row['month'] as int] = (row['total'] as num).toInt();
    }
    return result;
  }

  Map<String, int> topGenres({int limit = 5}) {
    final books = getBooksByStatus(ReadingStatus.finished);
    final genreCount = <String, int>{};
    for (final book in books) {
      for (final cat in book.categories) {
        genreCount[cat] = (genreCount[cat] ?? 0) + 1;
      }
    }
    final sorted = genreCount.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    return Map.fromEntries(sorted.take(limit));
  }

  List<Book> recentlyRead({int limit = 10}) {
    final rowIds = _db.select('''
      SELECT DISTINCT book_id FROM reading_sessions 
      WHERE end_time IS NOT NULL 
      ORDER BY end_time DESC 
      LIMIT ?
    ''', [limit]);

    final books = <Book>[];
    for (final row in rowIds) {
      final book = getBook(row['book_id'] as String);
      if (book != null) books.add(book);
    }
    return books;
  }

  /// Migration helper: adds title/author/cover_url columns to existing recommendations table.
  void _migrateRecommendationsTable() {
    for (final col in ['title', 'author', 'cover_url']) {
      try {
        _db.execute('ALTER TABLE recommendations ADD COLUMN $col TEXT');
      } catch (_) {
        // Column already exists — ignore
      }
    }
  }

  void close() {
    _db.dispose();
    _instance = null;
  }
}
